- type: replace
  path: /vm_extensions?
  value:
  - name: web_load_balancer
    cloud_properties:
      elbs:
      - ((web_load_balancer))
  - name: web_load_balancer2
    cloud_properties:
      elbs:
      - ((web_load_balancer2))
